#!/bin/bash
#cat ~/.ssh/id_rsa_mac17.pub | ssh root@${1} 'umask 077;mkdir -p ~/.ssh;cat >> ~/.ssh/authorized_keys'
cat ~/.ssh/id_rsa_mac17.pub | ssh ${1} 'umask 077;mkdir -p ~/.ssh;cat >> ~/.ssh/authorized_keys'
